### ISSUE TITLE
Parallax video doesn't get updated on Instagram

### ISSUE THREAD

**Issue by derek-xia** [cyrildiagne/instagram-3d-photo#1]
Pretty cool stuff! Somebody linked this on reddit and I had to try it out. The worker was creating the parallax video but was giving an error afterwards before uploading to the gcp bucket. I was able to fix it by changing the line in the colab notebook 
`video_file = output_folder + '/video/img_scroll.mp4'` to 
`video_file = output_folder + '/video/img_circle.mp4'`.

**Comment by ehsan886** [comment]
Hey, @derek-xia. I am sorry to bother you about this but I am at a dead-end trying to work this project. Could you please guide me a little as to what to do when "Enable CORS on bucket" and afterwards?

**Comment by derek-xia** [comment]
Yeah, no problem! After you've created the project and run the above commands, you need create a bucket using Cloud Storage and then you can follow 1. and 2. here under "[Configuring CORS on a bucket](https://cloud.google.com/storage/docs/configuring-cors#configure-cors-bucket)". (If you've done the above steps I assume you have google-cloud-sdk installed and can run gsutil.)

Then, there's a link in the .ipynb to a google colab notebook where you can follow all the instructions there to get it working. The last cell in the notebook runs a service which does all the computer vision stuff, but you need to change the line that I mentioned for it to work properly.

For the chrome extension, you need to go into developer mode and then click "load unpacked" in the extensions menu and load the extensions folder.

Then, you need to pip install everything in the backend folder and run main.py. It actually also didn't work for me and I had to run `export GOOGLE_APPLICATION_CREDENTIALS=<path to insta3d-colab-key.json>` for it to work.

Once you get everything working, run the last cell in the colab notebook and main.py and then when you go on Instagram and then click the extension icon it should start the video creation in the colab notebook. When it's done, click the extension icon again and it should change the images to parallax videos.

**Comment by ehsan886** [comment]
Wow! Thanks a lot for this. Hats off to you for figuring this out completely by yourself. Would you mind if I comment of the link of this page to the reddit post? There's a lot of people stuck trying to do it.

**Comment by derek-xia** [comment]
Go for it!

**Comment by cyrildiagne** [comment]
Thanks a lot @derek-xia for the detailed explaination. It will help me improve the documentation too.

**Comment by cyrildiagne** [comment]
Done, thanks again!
