### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by theredwillow** [cyrildiagne/instagram-3d-photo#2]
I have no way of knowing if Reddit user [u/RichardRNN](https://www.reddit.com/user/RichardRNN/) is the same person as this project's main contributor, cyrildiagne. However, it has been shared [here]( https://www.reddit.com/r/MachineLearning/comments/g4n9gz/p_a_chrome_extension_that_turns_every_instagram/) where users may not know how to use programming technology like git and gcloud. Could you consider updating your readme file to be a bit more layman?

**Comment by cyrildiagne** [comment]
Hi @theredwillow ,

First of all, apologies for the poor documentation, it is definitely not enough to run the project without strong knowledge of the Google Cloud Platform.
I will take some time this weekend to improve it and will put a warning until then.

Best,

**Comment by cyrildiagne** [comment]
I've done a first pass to improve the documentation. Please reopen if there are still areas missing.
Thanks,
