### ISSUE TITLE
Duplicate line/no subscription created

### ISSUE THREAD

**Issue by fkraeutli** [cyrildiagne/instagram-3d-photo#5]
I'm not very familiar with the Google Cloud platform, but it doesn't look like this line creates a subscription. It's a duplicate of line 26

https://github.com/cyrildiagne/instagram-3d-photo/blob/9999a0ab18cc19c355f373e1c48bf57a06f52861/scripts/create_pubsub.sh#L29

**Comment by cyrildiagne** [comment]
Yes good call, thanks!

Fixed in 366515c0bb0cdf0e6b54c9e470a259ce13655413.
